@startuml
participant ":Human" as a
participant ":PersonalComputer" as b
activate a
a -> a : 1: use() : void
  activate a
  a -> b : 1.1: powerOn() : void
  activate b
  a <-- b 
  deactivate b
  a -> b : 1.2: display() : void
  activate b
  a <-- b
  deactivate b
  a -> b : 1.3: powerOff() : void
  activate b
  a <-- b
  deactivate b
